### PR TITLE
Fixed NPE when getting flairs

### PR DESCRIPTION
**Pull request by alisolarflare**
Side effect: reduced Legendosh bug to happen every 10 seconds. I suspect
the author variable is null

### CODE REVIEW

**Comment by NorbiPeti** [comment]
You're 7 commits behind though... 😛  I'm fairly sure I fixed this yesterday.

**Comment by NorbiPeti** [comment]
Please check if the latest version errors for you.

**Comment by alisolarflare** [comment]
No, the master branch still errors like hell for me, check the post on #bot-room

**Comment by NorbiPeti** [comment]
It looks like getFlairState errors now... I'll fix that later today.

The reason I don't really want to accept this PR because these aren't *supposed* to be null at all.

**Pull request closed without merging**
